### ISSUE TITLE
nssm 的卸载调用

### ISSUE THREAD

**Issue by yaohappiness** [happynclient/happynwindows#16]
非常感谢提供这么方便好用的工具！

如果没有安装 nssm 服务，点了卸载服务，卸载程序会卡住。图形界面的提示也不友好，应该让卸载程序判断是否已经安装服务。

**Comment by happyntec** [comment]
谢谢反馈问题；

您反馈的问题我昨天也发现了，已经修掉了，计划包含在1.0.9版本里; 请耐心等一下

**Comment by happyntec** [comment]
已经发布 Release1.0.9 修正此问题:
https://github.com/happynclient/happynwindows/releases/tag/1.0.9-zh-cn
