### ISSUE TITLE
Required source code for happynportfwd.exe, happynroute.exe, happynssm.exe

### ISSUE THREAD

**Issue by procoder17** [happynclient/happynwindows#42]
Hi @happynclient
First, I'd like to thank you for this great project.
I want you to share the source code for happynportfwd.exe, happynroute.exe, happynssm.exe as well.
Thank you again.

**Comment by happyntec** [comment]
happynportfwd, happynroute folked from n2n, source repo:

https://github.com/happynlab/n2n


happynssm folk from nssm.cc:

https://github.com/happynlab/nssm
