### ISSUE TITLE
连接成功了  但是ip文本没有正常显示成功

### ISSUE THREAD

**Issue by chenyouxiu** [happynclient/happynwindows#45]
![image](https://github.com/happynclient/happynwindows/assets/42159346/cf29a8ed-32f6-4b2f-b07f-0bf5e2fa5718)

**Comment by happyntec** [comment]
您好，我看log可能是说服务端它不支持自动获取IP，您需要手工设置一个ip；

或者您安装了其它的虚拟网络的软件冲突了，可以参考这里解决：
https://happyncn.feishu.cn/wiki/wikcnbd4etMnGoKNTqJFflTKrsb

**Comment by chenyouxiu** [comment]
不是的  他已经获取到了我设置的dhcp ip地址  但是他没有帮我显示出来

**Comment by happyntec** [comment]
> 不是的 他已经获取到了我设置的dhcp ip地址 但是他没有帮我显示出来

那我想到的可能就是您安装了其它的有虚拟网络功能的软件，比如一些游戏加速器或者分流工具之类的软件，造成冲突了；

可以手工绑定一下虚拟网卡试试，请参考我上面给出的链接；
