### ISSUE TITLE
Network created with latest development revision of n2n causes included happyedge to crash.

### ISSUE THREAD

**Issue by eebssk1** [happynclient/happynwindows#47]
RT.
connect to latest dev version of edge and supernode causes inbuilt edge client to random crash (frequently).

**Comment by happyntec** [comment]
By default, we currently only support N2N 3.0; If you are using an other version of N2N (such as N2N V2 or latest version); You can also change the file a little by yourself to support, it's easy:

Prepare your N2N edge.exe

Rename your edge.exe to happynedge.exe to replace happynet's default installation file: `C:\Program Files (x86)\happynet\happynedge.exe`

Most parameters of N2N V2 and V3 are compatible. If there are special parameters that are not compatible, you can go to "Custom Parameters" in Advanced Settings to set your own parameters

**Comment by eebssk1** [comment]
Thanks.
It looks like N2N bug because it still randomly crash with latest one.
https://github.com/ntop/n2n/issues/1165
