### ISSUE TITLE
能否支持tcp转发

### ISSUE THREAD

**Issue by happytrudy** [happynclient/happynwindows#51]
https://bugxia.com/3439.html

网站提供了一个思路 可否集成到这个客户端里面 当选择强制走tcp中转时候的时候 启动 over_gnb程序

**Comment by brain-zhang** [comment]
我看了一下；这个需要服务端、客户端都运行这个over_gnb；

其实按照文章里面的说明，现在也可以手工服务端启动一个，客户端启动一个，然后用happyn去连接这个本地的映射后的端口，一样可以的；动手能力强的可以自助，如果集成到客户端里面，又得增加一堆说明；

这个方法其实是因为windows n2n不支持TCP造成的，而windows n2n不支持，是因为打洞需要UDP，而通过TCP打洞，需要一个比较高级的socket特性，目前在linux平台是可以的，但是windows平台，好像win7就不支持；

最根本的解决方法应该是让windows n2n原生支持TCP通信，这个feature等有时间了可以研究一下怎么做；

**Comment by happytrudy** [comment]
我的意思把他两集成到一起



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月6日(周五) 下午5:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [happynclient/happynwindows] 能否支持tcp转发 (Issue #51)




 
我看了一下；这个需要服务端、客户端都运行这个over_gnb；
 
其实按照文章里面的说明，现在也可以手工服务端启动一个，客户端启动一个，然后用happyn去连接这个本地的映射后的端口，一样可以的；动手能力强的可以自助，如果集成到客户端里面，又得增加一堆说明；
 
这个方法其实是因为windows n2n不支持TCP造成的，而windows n2n不支持，是因为打洞需要UDP，而通过TCP打洞，需要一个比较高级的socket特性，目前在linux平台是可以的，但是windows平台，好像win7就不支持；
 
最根本的解决方法应该是让windows n2n原生支持TCP通信，这个feature等有时间了可以研究一下怎么做；

**Comment by brain-zhang** [comment]
这个东东需要客户端和服务端都运行吧，我觉得动手能力强的可以自己运行搞定；集成之后还要增加说明，目前没精力做

**Comment by happytrudy** [comment]
好吧 linux很好搞 直接一个docker就行 看了这个程序C++ 我不会这个语言 所以请求帮忙

**Comment by happyntec** [comment]
我看了一下；这个需要服务端、客户端都运行这个over_gnb；

其实按照文章里面的说明，现在也可以手工服务端启动一个，客户端启动一个，然后用happyn去连接这个本地的映射后的端口，一样可以的；动手能力强的可以自助，如果集成到客户端里面，又得增加一堆说明；

可以列为backlog，您有时间可以测试一下，这个东东稳定不，如果稳定的话，可以考虑增加一个脚本，打包的时候作为一个三方工具集成一下；

**Comment by happytrudy** [comment]
测试了下 不稳定gnb这个 n2n v3 
自己本身支持-S1 参数 强制走supernode udp中转
自己本身支持-S2 参数 强制走supernode tcp中转
但是bug侠说window不支持 但是星空组网是n2n二开项目 他的window客户端就支持 配置tcp中转还是udp中转
![image](https://github.com/user-attachments/assets/6ceb4c8b-bb0e-4525-9a36-4f35f53f88ce)

**Comment by happyntec** [comment]
这个windows支持TCP我知道可以做的，这个需要用到一个比较高级的socket调用，不过目前没有时间，等过了年有时间会搞一搞

**Comment by happytrudy** [comment]
这个我看了n2n项目有人提了issue作者说做不了，不知道难点在哪里，星空组网人家已经做出来了，我在n2n上提了这个issue 查看了星空的进程 没有发现使用udp over tcp的工具
https://github.com/ntop/n2n/issues/1189

**Comment by happyntec** [comment]
这个是一个兼容性的问题，就是windows平台早期不支持SO_REUSEPORT这个socket选项；而要用tcp端口复用udp打洞端口，就必须同一个地址+端口绑定两个listen()调用；

早期n2n应该是考虑兼容性的问题，就没有支持；现在windows基本是都是win10以上了，就可以做了；应该没有多大工作量，就是需要测试；您有兴趣可以实现一下；

目前这个软件用户不多，做这个feature意义不大，所以暂时没有太大精力投入这上面了；
